# Generated by Django 4.0.5 on 2022-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('atc', 'Altcoin')], default='btc', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.URLField()),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrency News',
                'unique_together': {('title', 'publish_date')},
            },
        ),
    ]
