# Generated by Django 4.0.5 on 2022-06-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_cryptocurrencynews_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencynews',
            name='path',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
