# Generated by Django 4.0.5 on 2022-06-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0003_alter_cryptocurrencynews_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrencynews',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cryptocurrencynews',
            unique_together=set(),
        ),
    ]
